apiVersion: v1

kind: Service

metadata:
  name: codegenweb
  namespace: codegen-ns

spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP

  selector:
    app: codegenweb
