{
 "title": "Code generator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Generate apps requests rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(codegen_generated_apps_requests_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Generate apps request duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(codegen_generated_apps_request_duration_seconds_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Generate guids requests rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(codegen_guids_requests_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Generate guids request duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(codegen_guids_request_duration_seconds_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Guid generator total requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "codegen_guids_generated_total" }
   ]
  }
 ]
}